import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import NftTransaction from '../requests/mint'
import { TransactionList } from '../components/TransactionList'
import { CollectionDetails } from '../components/CollectionDetails'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          A real-time <a href="https://www.y00ts.com/">y00ts</a> dashboard
        </h1>

        <br />

        <img src="/y00ts-logo.svg" />

        < br />

        <CollectionDetails />

        <TransactionList />

      </main>
    </div>
  )
}
